

topicarray = ["Soft skills",
"Empathy",
"Teamwork",
"Time management",
"Hard skills",
"Web  development",
"Client-server",
"HTTP",
"Request-response cycle",
"Methods",
"Status codes",
"Headers",
"Charsets",
"State",
"Cookies",
"Sessions",
"OSI  Layers",
"Routing",
"Packets",
"Caching",
"URIs",
"URLs",
"URNs",
"APIs",
"JSON",
"XML",
"REST",
"Restful CRUD",
"HATEOAS",
"Separation  of  concerns",
"Semantics/function",
"HTML",
"DOM",
"Character and entity  references",
"Semantics",
"XML",
"XSD/DTD",
"Valid vs. well-formed",
"XPath/XSL/XQuery",
"Validation (W3C  validator)",
"Hypertext",
"Templating",
"ERB",
"Haml/Jade/Slim",
"EJS",
"Handlebars/mustache",
"Presentation",
"CSS",
"Selectors",
"Specificity",
"Blocks",
"Properties",
"Namespaces",
"Inheritance/the  cascade",
"Transformations",
"Box  model",
"Color model",
"RGB",
"HSB",
"HSL",
"CMYK",
"Positioning",
"Media  queries",
"Frameworks",
"Foundation",
"Bootstrap",
"Materialize",
"Preprocessors",
"Sass",
"LESS",
"Stylus",
"Themes/templates",
"Progressive  enhancement",
"Responsive web design",
"Grid design  and layout",
"Typography",
"Typefaces",
"Serif",
"Sans-serif",
"Monospaced (typewriter)",
"Script/blackletter/decorative",
"Symbol",
"Fonts",
"Size",
"Weight"
"Style",
"Variant",
"Embedded fonts",
"Validation (W3C  validator)",
"XSL",
"XSLT",
"XSL-FO",
"Behavior/interactivity",
"JavaScript (CoffeeScript)",
"jQuery & jQuery  UI",
"Libraries  vs. frameworks",
"Underscore,  lodash, and ramda",
"AJAX",
"Accessibility/Usability",
"ARIA",
"Persistence",
"ORMs",
"ActiveRecord",
"Mongoid/etc.",
"SQL  Bricks",
"ODMs",
"Databases",
"RDBMSs",
"PostgreSQL",
"SQLite3",
"MySQL",
"Document",
"MongoDB",
"CouchDB",
"RethinkDB",
"Graph",
"OrientDB",
"ArangoDB",
"Key-value",
"Redis",
"SQL",
"DDL",
"DML",
"ACL",
"Graphs",
"Traversals",
"Blueprint/Tinkerpop/etc.",
"Djikstra",
"UX",
"Programming",
"Fundamentals",
"Values,  variables,  expressions,  statements",
"Scope",
"Mutability and immutability",
"Referential  transparency",
"Substitution",
"Conditionals",
"Pattern  matching",
"Loops",
"List comprehensions",
"Types",
"Type systems:  strong  vs. weak",
"Type checking: static  vs. dynamic",
"Polymorphism and duck  typing",
"Algebraic  data  types",
"Meta-programming and monkey  patching",
"Type safety",
"Functions",
"Recursion",
"Paradigms",
"Imperative vs. declarative",
"OOP",
"Class  vs. prototype",
"Encapsulation",
"Composition  vs. inheritance vs. delegation",
"Polymorphism",
"SOLID",
"Single responsibility  principle",
"Open/closed principle",
"Liskov substitution  principle",
"Interface segregation principle",
"Dependency inversion principle",
"Design patterns",
"Creational",
"Structural",
"Behavioral",
"Responsibility- vs.  data-driven design",
"AOP and  cross-cutting concerns",
"FP",
"The  lambda  calculus",
"First  class functions",
"Higher order functions",
"Purity and side-effects",
"Strict vs. non-strict  evaluation  (laziness)",
"Compositionality",
"FRP",
"Discrete vs. continuous",
"Push vs. pull",
"Procedural",
"Methodologies",
"Agile",
"Kanban",
"Scrum",
"Lean",
"TDD/BDD",
"XP",
"Alternatives",
"Waterfall",
"Spiral",
"Rapid  Application Development (RAD)",
"Cowboy coding",
"Theory",
"Turing machines",
"The  Halting Problem",
"The  Rule  of  Least Power",
"Gödel’s  Incompleteness  Theorem",
"The  Liar’s  Paradox",
"Undecidable  statements",
"Turing completeness",
"Algorithms",
"Binary search",
"Sorting",
"Selection",
"Insertion",
"Recursive  algorithms",
"Towers of  Hanoi",
"Factorial",
"Sorting",
"Merge",
"Quick",
"Bubble",
"Graph  traversal",
"Tree traversal",
"Asymptotic notation",
"Big-O"]

topicarray.each do |x|
  Topic.create(name: x)
end
